CREATE TABLE IF NOT EXISTS "COBRO_COMISION_LOTE" (
    "ID_COBRO_COMISION" UUID PRIMARY KEY,
    "ID_EVENTO_ORIGEN" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80),
    "TOTAL_LINEAS" INTEGER NOT NULL,
    "LINEAS_ON_US_ACREDITADAS" INTEGER NOT NULL,
    "LINEAS_OFF_US_INCLUIDAS" INTEGER NOT NULL,
    "LINEAS_RECHAZADAS" INTEGER NOT NULL,
    "LINEAS_FALLIDAS" INTEGER NOT NULL,
    "LINEAS_COBRABLES" INTEGER NOT NULL,
    "MONTO_CONTROL" NUMERIC(18, 2),
    "MONTO_PROCESADO" NUMERIC(18, 2) NOT NULL,
    "MONTO_REMANENTE" NUMERIC(18, 2),
    "MONEDA" VARCHAR(3) NOT NULL,
    "TARIFA_UNITARIA" NUMERIC(18, 2) NOT NULL,
    "SUBTOTAL_COMISION" NUMERIC(18, 2) NOT NULL,
    "ESTADO" VARCHAR(40) NOT NULL,
    "ESTADO_RESPUESTA_CORE" VARCHAR(40),
    "ID_COBRO_COMISION_CORE" VARCHAR(80),
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "MONTO_IMPUESTO" NUMERIC(18, 2),
    "MONTO_TOTAL_COBRADO" NUMERIC(18, 2),
    "MENSAJE_RESPUESTA_CORE" VARCHAR(500),
    "EVENTO_COBRO_COMPLETADO_PUBLICADO" BOOLEAN NOT NULL,
    "ID_EVENTO_COBRO_COMPLETADO" UUID,
    "FECHA_RECEPCION" TIMESTAMPTZ NOT NULL,
    "FECHA_CALCULO" TIMESTAMPTZ,
    "FECHA_SOLICITUD_CORE" TIMESTAMPTZ,
    "FECHA_RESPUESTA_CORE" TIMESTAMPTZ,
    "FECHA_FINALIZACION" TIMESTAMPTZ,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "COBRO_COMISION_LOTE"
    ADD COLUMN IF NOT EXISTS "ID_FONDEO_CORE" VARCHAR(80);

CREATE TABLE IF NOT EXISTS "CALCULO_COMISION" (
    "ID_CALCULO_COMISION" UUID PRIMARY KEY,
    "ID_COBRO_COMISION" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "LINEAS_COBRABLES" INTEGER NOT NULL,
    "TARIFA_UNITARIA" NUMERIC(18, 2) NOT NULL,
    "SUBTOTAL_COMISION" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "FECHA_CALCULO" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SOLICITUD_COBRO_CORE" (
    "ID_SOLICITUD_COBRO_CORE" UUID PRIMARY KEY,
    "ID_COBRO_COMISION" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "CLAVE_IDEMPOTENCIA" VARCHAR(80) NOT NULL UNIQUE,
    "ESTADO_SOLICITUD" VARCHAR(40) NOT NULL,
    "MONTO_SOLICITADO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "ESTADO_RESPUESTA_CORE" VARCHAR(40),
    "ID_COBRO_COMISION_CORE" VARCHAR(80),
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "MONTO_IMPUESTO" NUMERIC(18, 2),
    "MONTO_TOTAL_COBRADO" NUMERIC(18, 2),
    "MENSAJE_RESPUESTA_CORE" VARCHAR(500),
    "FECHA_SOLICITUD" TIMESTAMPTZ NOT NULL,
    "FECHA_RESPUESTA" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "AJUSTE_FONDEO" (
    "ID_AJUSTE_FONDEO" UUID PRIMARY KEY,
    "ID_COBRO_COMISION" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "ID_FONDEO_CORE" VARCHAR(80),
    "MONTO_REMANENTE" NUMERIC(18, 2) NOT NULL,
    "MONTO_LIBERADO" NUMERIC(18, 2),
    "MONEDA" VARCHAR(3) NOT NULL,
    "ESTADO" VARCHAR(40) NOT NULL,
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "ESTADO_RESPUESTA_CORE" VARCHAR(40),
    "MENSAJE_RESPUESTA_CORE" VARCHAR(500),
    "CLAVE_IDEMPOTENCIA" VARCHAR(80) NOT NULL UNIQUE,
    "FECHA_SOLICITUD" TIMESTAMPTZ,
    "FECHA_FINALIZACION" TIMESTAMPTZ,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_COBRO_COMISION_LOTE"
    ON "COBRO_COMISION_LOTE" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_COBRO_COMISION_ESTADO"
    ON "COBRO_COMISION_LOTE" ("ESTADO");

CREATE INDEX IF NOT EXISTS "IDX_CALCULO_COMISION_LOTE"
    ON "CALCULO_COMISION" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_SOLICITUD_COBRO_CORE_LOTE"
    ON "SOLICITUD_COBRO_CORE" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_AJUSTE_FONDEO_LOTE"
    ON "AJUSTE_FONDEO" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_AJUSTE_FONDEO_ESTADO"
    ON "AJUSTE_FONDEO" ("ESTADO");
